// src/context/ThemeContext.jsx

import React, { createContext, useState, useEffect, useContext } from 'react';

// 创建主题和语言上下文
export const ThemeContext = createContext();

// 语言包
export const languages = {
  zh: {
    appName: "ReaText",
    tagline: "拍照识别",
    takePhoto: "拍照",
    uploadImage: "上传图片",
    batchRecognition: "批量识别",
    enableFloatingBall: "启用悬浮球",
    translation: "PDF识别",
    offlineMode: "离线记录",
    darkMode: "深色模式",
    enabled: "已启用",
    networkOffline: "您当前处于离线状态，部分功能可能不可用",
    settings: "设置",
    language: "语言选择",
    recognizing: "正在识别文字...",
    recognitionResult: "识别结果",
    copyAll: "复制全部",
    translateText: "翻译文本",
    retake: "重新拍照",
    editText: "编辑文字",
    save: "保存",
    copied: "文字已复制！",
    keepStable: "请将文字对准框内，保持稳定",
    clickToSelect: "点击选择图片",
    supportFormats: "支持 PNG、JPG 格式",
    selectImage: "选择图片",
    startRecognition: "开始识别",
    selectTargetLanguage: "选择您想要翻译的目标语言",
    originalText: "原文",
    translationResult: "翻译结果",
    translating: "翻译中...",
    resultWillShowHere: "翻译结果将显示在这里",
    resultCopied: "翻译结果已复制！",
    changeLanguage: "更换语言",
    close: "关闭",
    cancel: "取消",
    supportInfo: "支持中英文识别，可以拍摄文档、书籍、名片等",
    newFeature: "支持PDF文档识别和批量处理功能！",
    privacyPolicy: "隐私政策",
    termsConditions: "使用条款",
    copyright: "© 2025 闪识 OCR - 快速文字识别",
    recognizingPdf: "正在识别 PDF，请稍候...",
    processingPdf: "正在处理 PDF 文档，请稍候...",
    page: "页",
    addImage: "添加图片",
    selectImagesInfo: "请选择要识别的图片（最多9张）",
    batchHint: "支持多张图片识别，批量处理提高效率",
    preprocessingOptions: "图像预处理选项",
    contrast: "对比度",
    brightness: "亮度",
    sharpness: "锐化",
    denoise: "降噪",
    autoRotate: "自动旋转",
    resetDefaults: "重置为默认值",
    loadHistoryError: "加载历史失败：",
    history: "历史记录",
    searchHistory: "搜索历史记录…",
    historyRecord: "历史记录",
    readMore: "阅读全文",
    collapse: "收起",
    confirmDelete: "确定要删除这条记录吗？",
    copySuccess: "文字已复制到剪贴板",
    noHistory: "暂无历史记录",
    batchResults: "批量识别结果",
    resultImageAlt: "识别图片",
    pdfPage: "PDF 页",
    originalImageLabel: "原始图像",
    optimizedImageLabel: "优化图像",
    backToUpload: "返回上传",
    pdfResults: "PDF 识别结果",
    pagePrefix: "第",
    pageSuffix: "页",
    translationFailed: "[翻译失败]",
    clearHistory: "清空历史",
    confirmClearHistory: "确定要清空所有历史记录吗？",
    imagesSelected: "已选择 {count} 张图片",
    processing: "正在处理中...",
    maxHistoryRecords: "最多 100 条历史记录"
  },
  en: {
    appName: "ReaText",
    tagline: "Scan Text instantly",
    takePhoto: "Camera",
    uploadImage: "Upload Image",
    batchRecognition: "Batch Recognition",
    enableFloatingBall: "Enable Floating Ball",
    translation: "PDF Scan",
    offlineMode: "Offline",
    darkMode: "Dark Mode",
    enabled: "Enabled",
    networkOffline: "You are currently offline. Some features may be unavailable.",
    settings: "Settings",
    language: "Language",
    recognizing: "Recognizing text...",
    recognitionResult: "Recognition Result",
    copyAll: "Copy All",
    translateText: "Translate",
    retake: "Retake",
    editText: "Edit Text",
    save: "Save",
    copied: "Text copied!",
    keepStable: "Keep the text within frame and hold steady",
    clickToSelect: "Click to select image",
    supportFormats: "PNG, JPG formats supported",
    selectImage: "Select Image",
    startRecognition: "Start Recognition",
    selectTargetLanguage: "Select your target language",
    originalText: "Original Text",
    translationResult: "Translation Result",
    translating: "Translating...",
    resultWillShowHere: "Translation will appear here",
    resultCopied: "Translation copied!",
    changeLanguage: "Change Language",
    close: "Close",
    cancel: "Cancel",
    supportInfo: "Supports both Chinese and English recognition for documents, books, and cards",
    newFeature: "PDF document recognition and batch processing support!",
    privacyPolicy: "Privacy Policy",
    termsConditions: "Terms of Use",
    copyright: "© 2025 FlashOCR - Fast Text Recognition",
    recognizingPdf: "Recognizing PDF, please wait...",
    processingPdf: "Processing PDF document, please wait...",
    page: "Page",
    addImage: "Add Image",
    selectImagesInfo: "Please select images to recognize (up to 9)",
    batchHint: "Supports multiple images and PDF documents; batch processing for efficiency",
    preprocessingOptions: "Image Processing Options",
    contrast: "Contrast",
    brightness: "Brightness",
    sharpness: "Sharpen",
    denoise: "Denoise",
    autoRotate: "Auto Rotate",
    resetDefaults: "Reset to Defaults",
    loadHistoryError: "Failed to load history:",
    history: "History",
    searchHistory: "Search history...",
    historyRecord: "History record",
    readMore: "Read more",
    collapse: "Collapse",
    confirmDelete: "Are you sure you want to delete this record?",
    copySuccess: "Text copied to clipboard",
    noHistory: "No history records",
    batchResults: "Batch Recognition Results",
    resultImageAlt: "Recognized Image",
    pdfPage: "PDF Page",
    originalImageLabel: "Original Image",
    optimizedImageLabel: "Optimized Image",
    backToUpload: "Back to Upload",
    pdfResults: "PDF Recognition Results",
    pagePrefix: "Page ",
    pageSuffix: "",
    translationFailed: "[Translation failed]",
    clearHistory: "Clear History",
    confirmClearHistory: "Are you sure you want to clear all history records?",
    imagesSelected: "Selected {count} images",
    processing: "processing...",
    maxHistoryRecords: "Maximum of 100 history records"
  },
  'ms-MY': {
    appName: "ReaText",
    tagline: "Imbas Teks Serta-merta",
    takePhoto: "Kamera",
    uploadImage: "Muat Naik",
    batchRecognition: "Imbasan Kumpulan",
    enableFloatingBall: "Aktifkan Bola Terapung",
    translation: "Imbas PDF",
    offlineMode: "Luar Talian",
    darkMode: "Mod Gelap",
    enabled: "Diaktifkan",
    networkOffline: "Anda sedang luar talian. Sesetengah ciri mungkin tidak tersedia.",
    settings: "Tetapan",
    language: "Bahasa",
    recognizing: "Mengenali teks...",
    recognitionResult: "Keputusan Pengecaman",
    copyAll: "Salin Semua",
    translateText: "Terjemah",
    retake: "Ambil Semula",
    editText: "Sunting Teks",
    save: "Simpan",
    copied: "Teks disalin!",
    keepStable: "Pastikan teks dalam bingkai dan pegang stabil",
    clickToSelect: "Klik untuk pilih imej",
    supportFormats: "Menyokong format PNG, JPG",
    selectImage: "Pilih Imej",
    startRecognition: "Mula Pengecaman",
    selectTargetLanguage: "Pilih bahasa sasaran anda",
    originalText: "Teks Asal",
    translationResult: "Hasil Terjemahan",
    translating: "Menerjemah...",
    resultWillShowHere: "Terjemahan akan dipaparkan di sini",
    resultCopied: "Terjemahan disalin!",
    changeLanguage: "Tukar Bahasa",
    close: "Tutup",
    cancel: "Batal",
    supportInfo: "Menyokong pengecaman Cina dan Inggeris untuk dokumen, buku, kad",
    newFeature: "Sokongan imbasan dokumen PDF dan pemprosesan kumpulan!",
    privacyPolicy: "Polisi Privasi",
    termsConditions: "Terma Penggunaan",
    copyright: "© 2025 SnapText OCR",
    recognizingPdf: "Mengenali PDF, sila tunggu...",
    processingPdf: "Memproses dokumen PDF, sila tunggu...",
    page: "Halaman",
    addImage: "Tambah Imej",
    selectImagesInfo: "Sila pilih imej untuk diimbas (maksimum 9)",
    batchHint: "Menyokong berbilang imej dan dokumen PDF; pemprosesan kumpulan untuk kecekapan",
    preprocessingOptions: "Pilihan Pra-pemprosesan Imej",
    contrast: "Kontras",
    brightness: "Kecerahan",
    sharpness: "Ketajaman",
    denoise: "Mengurangkan hingar",
    autoRotate: "Putar Automatik",
    resetDefaults: "Tetapkan semula kepada lalai",
    loadHistoryError: "Gagal memuatkan sejarah:",
    history: "Sejarah",
    searchHistory: "Cari sejarah...",
    historyRecord: "Rekod Sejarah",
    readMore: "Baca Lagi",
    collapse: "Sempitkan",
    confirmDelete: "Adakah anda pasti mahu memadam rekod ini?",
    copySuccess: "Teks disalin ke papan klip!",
    noHistory: "Tiada rekod sejarah",
    batchResults: "Keputusan Imbasan Kumpulan",
    resultImageAlt: "Imej Diimbas",
    pdfPage: "Halaman PDF",
    originalImageLabel: "Imej Asal",
    optimizedImageLabel: "Imej Dioptimumkan",
    backToUpload: "Kembali ke Muat Naik",
    pdfResults: "Keputusan PDF",
    pagePrefix: "Halaman ",
    pageSuffix: "",
    translationFailed: "[Terjemahan gagal]",
    clearHistory: "Kosongkan Sejarah",
    confirmClearHistory: "Adakah anda pasti mahu mengosongkan semua rekod sejarah?",
    imagesSelected: "Dipilih {count} imej",
    processing: "sedang memproses...",
    maxHistoryRecords: "Maksimum 100 rekod sejarah"
  },
  'hi-MY': {
    appName: "ReaText",
    tagline: "पाठ तुरंत स्कैन करें",
    takePhoto: "कैमरा",
    uploadImage: "अपलोड इमेज",
    batchRecognition: "बैच स्कैन",
    enableFloatingBall: "तैरती गेंद सक्षम करें",
    translation: "पीडीएफ स्कैन",
    offlineMode: "ऑफ़लाइन मोड",
    darkMode: "डार्क मोड",
    enabled: "सक्षम",
    networkOffline: "आप ऑफ़लाइन हैं। कुछ सुविधाएँ उपलब्ध नहीं हो सकती हैं।",
    settings: "सेटिंग्स",
    language: "भाषा",
    recognizing: "पाठ पहचान रहा है...",
    recognitionResult: "पहचान परिणाम",
    copyAll: "सभी कॉपी करें",
    translateText: "अनुवाद करें",
    retake: "पुनः लें",
    editText: "पाठ संपादित करें",
    save: "सहेजें",
    copied: "पाठ कॉपी हो गया!",
    keepStable: "टेक्स्ट फ्रेम के अंदर रखें और स्थिर पकड़ें",
    clickToSelect: "इमेज चुनने के लिए क्लिक करें",
    supportFormats: "PNG, JPG प्रारूप समर्थित",
    selectImage: "इमेज चुनें",
    startRecognition: "पहचान शुरू करें",
    selectTargetLanguage: "अपनी लक्ष्य भाषा चुनें",
    originalText: "मूल पाठ",
    translationResult: "अनुवाद परिणाम",
    translating: "अनुवाद हो रहा है...",
    resultWillShowHere: "अनुवाद यहां दिखाई देगा",
    resultCopied: "अनुवाद कॉपी हो गया!",
    changeLanguage: "भाषा बदलें",
    close: "बंद करें",
    cancel: "रद्द करें",
    supportInfo: "दस्तावेज, पुस्तकें, कार्ड के लिए चीनी और अंग्रेजी पहचान का समर्थन करता है",
    newFeature: "PDF दस्तावेज़ पहचान और बैच प्रोसेसिंग समर्थन!",
    privacyPolicy: "गोपनीयता नीति",
    termsConditions: "उपयोग की शर्तें",
    copyright: "© 2025 SnapText OCR",
    recognizingPdf: "PDF की पहचान कर रहा है, कृपया प्रतीक्षा करें...",
    processingPdf: "PDF दस्तावेज़ संसाधित कर रहा है, कृपया प्रतीक्षा करें...",
    page: "पृष्ठ",
    addImage: "इमेज जोड़ें",
    selectImagesInfo: "पहचान के लिए इमेज चुनें (अधिकतम 9)",
    batchHint: "कई छवियों और PDF दस्तावेजों का समर्थन करें; कुशलता के लिए बैच प्रोसेसिंग",
    preprocessingOptions: "छवि प्रसंस्करण विकल्प",
    contrast: "विपरीतता",
    brightness: "उज्ज्वलता",
    sharpness: "तीक्ष्णता",
    denoise: "शोर कम करें",
    autoRotate: "स्वचालित घुमाएँ",
    resetDefaults: "डिफ़ॉल्ट पर रीसेट करें",
    loadHistoryError: "इतिहास लोड करने में विफल:",
    history: "इतिहास",
    searchHistory: "इतिहास खोजें...",
    historyRecord: "इतिहास रिकॉर्ड",
    readMore: "और पढ़ें",
    collapse: "संकुचित करें",
    confirmDelete: "क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?",
    copySuccess: "पाठ क्लिपबोर्ड में कॉपी किया गया!",
    noHistory: "कोई इतिहास रिकॉर्ड नहीं",
    batchResults: "बैच पहचान परिणाम",
    resultImageAlt: "पहचानी गई इमेज",
    pdfPage: "PDF पृष्ठ",
    originalImageLabel: "मूल छवि",
    optimizedImageLabel: "अनुकूलित छवि",
    backToUpload: "अपलोड पर वापस जाएं",
    pdfResults: "PDF पहचान परिणाम",
    pagePrefix: "पृष्ठ ",
    pageSuffix: "",
    translationFailed: "[अनुवाद विफल]",
    clearHistory: "सारी इतिहास साफ़ करें",
    confirmClearHistory: "क्या आप वाकई सभी इतिहास रिकॉर्ड साफ़ करना चाहते हैं?",
    imagesSelected: "{count} छवियाँ चुनी गईं",
    processing: "प्रक्रिया चल रही है...",
    maxHistoryRecords: "अधिकतम 100 इतिहास रिकॉर्ड"
  }
};

// 主题提供者组件
export const ThemeProvider = ({ children }) => {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [networkStatus, setNetworkStatus] = useState(navigator.onLine);
  const [currentLanguage, setCurrentLanguage] = useState('en');
  
  // 获取语言包
  const t = languages[currentLanguage];

  // 初始化主题设置
  useEffect(() => {
    const savedDarkMode = localStorage.getItem('darkMode') === 'true';
    const savedLanguage = localStorage.getItem('language') || 'en';
    setIsDarkMode(savedDarkMode);
    setCurrentLanguage(savedLanguage);
    if (savedDarkMode) document.documentElement.classList.add('dark');
    else document.documentElement.classList.remove('dark');
    const handleNetworkChange = () => setNetworkStatus(navigator.onLine);
    window.addEventListener('online', handleNetworkChange);
    window.addEventListener('offline', handleNetworkChange);
    return () => {
      window.removeEventListener('online', handleNetworkChange);
      window.removeEventListener('offline', handleNetworkChange);
    };
  }, []);
  
  const toggleDarkMode = () => {
    const newDarkMode = !isDarkMode;
    setIsDarkMode(newDarkMode);
    localStorage.setItem('darkMode', newDarkMode);
    if (newDarkMode) document.documentElement.classList.add('dark');
    else document.documentElement.classList.remove('dark');
  };
  
  const changeLanguage = (lang) => {
    setCurrentLanguage(lang);
    localStorage.setItem('language', lang);
  };
  
  return (
    <ThemeContext.Provider
      value={{
        isDarkMode,
        toggleDarkMode,
        isOnline: networkStatus,
        currentLanguage,
        changeLanguage,
        t
      }}
    >
      {children}
    </ThemeContext.Provider>
  );
};

// 自定义Hook
export const useTheme = () => useContext(ThemeContext);
