
create table if not exists "public"."6807108f7e14d9f5d6dbf8a3_history" (
  "id" bigint generated by default as identity,
  "user_id" uuid,
  "image_url" text,
  "text_content" text,
  "created_at" timestamp with time zone default now(),
  
  primary key ("id")
);

-- Add example data if needed
insert into "public"."6807108f7e14d9f5d6dbf8a3_history" ("image_url", "text_content", "created_at") 
values 
('https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=250', '会议记录：项目进度讨论及下一步工作安排', now() - interval '2 days'),
('https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?q=80&w=250', '重要通知：关于2025年公司年度计划的说明', now() - interval '3 days'),
('https://images.unsplash.com/photo-1572281149252-658fd6764e7d?q=80&w=250', '产品设计规范 v2.0：新界面设计指南', now() - interval '5 days');
  